apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: aartibhagtani/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:  
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: aartibhagtani/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:  
        '**/*.js': .
    - image: aartibhagtani/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:  
        '**/*.js': .
deploy:
  kubectl:
    manifests: 
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml
      # do not add in here the persistent data pods like postgres pods